version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
