version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster.mongodb.net/<dbname>
    depends_on:
      - frontend

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
